### PR TITLE
get objects test added

### PR DESCRIPTION
**Pull request by lauralilleste**

### CODE REVIEW

**Comment by lauriliivamagi** [comment]
For general remark: please do the 'git rebase master' on this branch to get the actual ability to run the tests.

**Comment by lauriliivamagi** [comment]
Ok, I did the git rebase myself and pushed it. Now the branch is up to date with 'master'.

**Comment by lauralilleste** [comment]
How can I export the server in my tests?

**Comment by lauriliivamagi** [comment]
I did the export part and lot more. Now the test actually works (if the app has connection to the database, which it currently doesn't in Travis CI).

**Comment by lauriliivamagi** [comment]
Ok, it seems to work now in Travis CI also. :)  I'm merging this branch to 'master' now.

**Pull request merged**
